---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-site
  labels:
    app: web-site
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-site
      tier: frontend
  template:
    metadata:
      labels:
        app: web-site
        tier: frontend
    spec:
      containers:
      - name: assesment-clops
        image: mohan1398/assesment_clops:latest
        ports:
        - containerPort: 8080
