---
apiVersion: v1
kind: Service
metadata:
  name: web-site
  labels:
    app: web-site
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: web-site
    tier: frontend

